### ISSUE TITLE
The osz parser is named incorrectly

### ISSUE THREAD

**Issue by nobbele** [iptq/libosu#2]
it's actually the .osu parser

**Comment by iptq** [comment]
Wanted to avoid using the name "osu" for the parser since it's such a common word in this repository, but i agree that osz isn't very descriptive. I want to make sure that this is distinct from the new format that lazer uses, so if you suggest a different name that meets those conditions then we can rename it

**Comment by nobbele** [comment]
osufile? beatmapfile? hard to think of anything good

**Comment by iptq** [comment]
On Fri, 2020-12-25 at 05:53 -0800, Nobbele wrote:
> osufile? beatmapfile? hard to think of anything good
> 

Hence "osz". I'll leave this open until we decide on a better name or
decide that osz is ok.

**Comment by iptq** [comment]
nvm renamed to parsing for now

**Comment by nobbele** [comment]
the thing that's most weird about this is that the function is called .as_osz, could it be named just .as_osu?
