### ISSUE TITLE
Unify time types

### ISSUE THREAD

**Issue by nobbele** [iptq/libosu#7]
Right now there's 4 different types used for time.

- TimestampMillis (wrapper over i32)
- i32 in object start time
- i64 in replay action time
- f64 in slider duration

It's really verbose to be casting between all of them, an i32 is sufficient for almost all use cases (only breaks above 25 days).
I think it should be a u32 if possible, but I don't know if negative times are used anywhere.

**Comment by iptq** [comment]
Timestamps are kinda fucked in OSU to begin with. If we unify the types in this library then it'll have to be a float type and then the integer conversions will just have to be done during serialization/deserialization. Negative times are probably used in editor but I'm not 100% sure.

I'm thinking of mimicking [`std::time`](https://doc.rust-lang.org/std/time/index.html), and having timestamps be more opaque than they are now, because it's really a huge pain converting between seconds/milliseconds. Then again this means implementing all basic arithmetic operations on top of these structs as well as any other operations that might be useful to dealing with time. In any case I _don't_ really want to think about mixing time types with other numeric types since it's basically the same as the boolean blindness problem.

**Comment by nobbele** [comment]
Timings points are common to be negative actually.
Slider duration and other floats can be rounded to int. Sub-millisecond accuracy shouldn't be necessary.

**Comment by iptq** [comment]
> Sub-millisecond accuracy shouldn't be necessary.

If we want structs like `Beatmap` and `Replay` to exactly represent what their on-disk representations are, and do no calculations on it, then sure. But in that case, I wouldn't use Millis on the other functions like slider duration (which is derived from bpm, sv, and pixel length) and things that are calculated _from_ the original values since for those we do need more precision.

**Comment by iptq** [comment]
Could you just change the slider duration function to return an f64 ? I think that should be ok

**Comment by nobbele** [comment]
should get_hitobject_end_time cast the duration to millis then?
